### ISSUE TITLE
Doesnt work yet

### ISSUE THREAD

**Issue by JanBdf** [Brionjv/TLOZ-A-Link-Between-Worlds-Save-Editor#2]
cant even load a file

**Comment by JanBdf** [comment]
btw if you read this id like to know how you know what the bytes mean
I mean how do you decode the file to change the values ?

**Comment by Brionjv** [comment]
with an hex editor, I edit save file and test on 3ds. 
You can test save editor, if you have empty save file when you restore your save file : reload your save file in the editor and click on save on top and restore save file
